### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by me-dervis** [unforgiventr/Kavi-Voice-Assistant#3]
**Kali-Linux 2019.3** sürümünde  

`Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from Modules.basemodules.py import Backend
ImportError: No module named Modules.basemodules.py
`
hatası alıyorum

**Comment by me-dervis** [comment]
> **Kali-Linux 2019.3** sürümünde
> 
> `Traceback (most recent call last): File "main.py", line 2, in <module> from Modules.basemodules.py import Backend ImportError: No module named Modules.basemodules.py `
> hatası alıyorum

Line 2 diyor çünkü ASCII hatası alıyordum bir kod ile düzelttim

**Comment by burakdeniz32** [comment]
Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\speech_recognition\__init__.py", line 108, in get_pyaudio
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/KaOS/Desktop/Kavi-Voice-Assistant-master/main.py", line 73, in <module>
    datax = mediamodule.recordAudio()
  File "c:\Users\KaOS\Desktop\Kavi-Voice-Assistant-master\Modules\basemodules.py", line 35, in recordAudio
    with sr.Microphone() as source:
  File "C:\Python3\lib\site-packages\speech_recognition\__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "C:\Python3\lib\site-packages\speech_recognition\__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation
-----------------------------------------------------------------------------------
hatası alıyorum nasıl düzeltebilirim teşekkürler

**Comment by xtcuser** [comment]
Merhaba Burak,
PyAudio modülünü yüklemen gerekiyor. Şunu terminaline yazıp tekrar dener misin?
pip install pyaudio
veya
pip3 install pyaudio


________________________________
Kimden: burakdeniz32 <notifications@github.com>
Gönderme tarihi: Cuma, Eylül 27, 2019 11:30 ÖS
Kime: yemregundogmus/Kavi-Voice-Assistant
Bilgi: Subscribed
Konu: Re: [yemregundogmus/Kavi-Voice-Assistant] Import Error (#3)


Traceback (most recent call last):
File "C:\Python3\lib\site-packages\speech_recognition_init_.py", line 108, in get_pyaudio
import pyaudio
ModuleNotFoundError: No module named 'pyaudio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "c:/Users/KaOS/Desktop/Kavi-Voice-Assistant-master/main.py", line 73, in
datax = mediamodule.recordAudio()
File "c:\Users\KaOS\Desktop\Kavi-Voice-Assistant-master\Modules\basemodules.py", line 35, in recordAudio
with sr.Microphone() as source:
File "C:\Python3\lib\site-packages\speech_recognition_init_.py", line 79, in init
self.pyaudio_module = self.get_pyaudio()
File "C:\Python3\lib\site-packages\speech_recognition_init_.py", line 110, in get_pyaudio
raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation

hatası alıyorum nasıl düzeltebilirim teşekkürler
