### ISSUE TITLE
Excel xlsx file; not supported

### ISSUE THREAD

**Issue by elsatmirdes** [unforgiventr/Kavi-Voice-Assistant#9]
Hata Kodunun Tamamı = 

Say something!
You said: nasılsın
Traceback (most recent call last):
  File "C:/Users/user/Desktop/Elşat/Speec/Kavi/main.py", line 74, in <module>
    data = pandas.read_excel("animsatici.xlsx")
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\io\excel\_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\io\excel\_base.py", line 824, in __init__
    self._reader = self._engines[engine](self._io)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\io\excel\_xlrd.py", line 21, in __init__
    super().__init__(filepath_or_buffer)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\io\excel\_base.py", line 353, in __init__
    self.book = self.load_workbook(filepath_or_buffer)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\io\excel\_xlrd.py", line 36, in load_workbook
    return open_workbook(filepath_or_buffer)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xlrd\__init__.py", line 170, in open_workbook
    raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported

Process finished with exit code 1

Bu hatayı nasıl düzeltirim?

**Comment by Peyxw** [comment]
Aynı Hata Bendede Oluştu Sebebini Bilmiyorum Bilen Varsa Lütfen Yaza Bilirmi

**Comment by recepavci** [comment]
Merhaba excel dosyasını bulamıyor dosya yolunu kontrol edin. Bende düzenli çalıştı sıkıntı görünmüyor. Fakat komutlar çalışmıyor. Benim söylediklerimi yazıyor o kadar ...

**Comment by yemregundogmus** [comment]
`pip install xlrd==1.2.0` yüklenerek çözülebilir
